### ISSUE TITLE
Godot needs GLTF without Draco compression

### ISSUE THREAD

**Issue by agajdosi** [BlenderKit/blenderkit_asset_tasks#22]
Godot nema support pro [Draco compressed](https://google.github.io/draco/) modely. Feature neplanuji pridat, protoze to vicemene nedava smysl, protoze by je stejne Godot rozbalil a hned prekonvertoval do sveho interniho formatu komprese. Kazdopadne pro web zase Draco smysl dava, takze mi z toho trochu vyskakuje to, ze bysme meli mit 2 formaty GLTF. Jedno nekomprimovany bez Draco a asi s lossless PNG texturama. A druhy komprimovany.

WDYT? @PetrDlouhy @vilemduha

**Comment by PetrDlouhy** [comment]
@agajdosi A zvládá tu kompresi ten webový prohlížeč? Já tam vidím tohle:
![Snímek obrazovky_2024-12-04_11-28-30](https://github.com/user-attachments/assets/af8eaff4-e27d-4354-887d-450624801ffc)

Na modelu chybí polovina vousů, čumáku, materiál očí a podobně.
Není to tou kompresí? Nebo čím to je?

**Comment by agajdosi** [comment]
@PetrDlouhy IDK. Ale pochybuju, ze format jako takovej nezvladne pulku fousu. Cele to bude spis o exportu, ktery je potreba dobre nastavit, aby vyhovoval co nejvice modelum - a to mi prijde jako jina issue.

Polovina fousu? Asi tam byl nejakej modifier, kterej se neuplatnil v ramci exportu.
Chybejici oci? Mozna procesualni material, kterej se spatne exportoval.

Vsechny zadrhely a okliky, ktere se muzou behem GLTF exportu podelat, a jak jim teda predejit (potreba aplikovat modifiers, zapeceni nebo jak se tomu rika procesualnich textur atd.) je otazka spis otazka na nekoho, kdo dela vylozene 3Dcko. @AdamKyber @vilemduha @Myska19

**Comment by agajdosi** [comment]
Kazdopadne pokud nechceme na webu davat preview 3D modelu skrze GLTF (protoze kdyz se to zobrazi v prohlizeci, tak se to da taky stahnout rovnou) ale spis ukazovat video otocky, pak je taky moznost proste Draco vypnout, smazat soucasne GLTF a pregenerovat.

**Comment by agajdosi** [comment]
Fousky na sobe maji mirror modifier, ktery nebyl aplikovanej vice budem resit tady: https://github.com/BlenderKit/blenderkit_asset_tasks/issues/23 K tematu komprese je to off topic.

**Comment by PetrDlouhy** [comment]
OK. Jestli chceme 2 verze GLTF, bude potřeba je na serveru nějak řešit, udělal jsem issue: https://github.com/BlenderKit/BlenderKit-server/issues/1162

**Comment by PetrDlouhy** [comment]
To jestli to chceme ukazovat lidem nebo ne je otázka. V případě free assetů v tom vlastně nevidím žádný problém a full planistům můžeme zobrazit cokoliv.
Je ale otázka, jestli dává smysl, když to bude zobrazené jen u těch free assetů.

**Comment by agajdosi** [comment]
PRko pridavajici gltf-godot mergnuto. Skocim na tenhle task brzo.

**Comment by agajdosi** [comment]
Implemented in https://github.com/BlenderKit/blenderkit_asset_tasks/pull/25 and https://github.com/BlenderKit/blenderkit_asset_tasks/pull/26.
